name: ft_cli
description: This project is one CLI for integrate Flutter and Dart with Clean Architecture
version: 0.1.5
homepage: https://github.com/jheimes-silveira/ft_cli

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.3.0
  get_it: ^7.2.0
  ansicolor: ^2.0.1
  recase: ^4.0.0
  process_run: ^0.12.2
  cli_dialog: ^0.5.0

dev_dependencies:
  test: ^1.16.5

executables:
  ft_cli: ft_cli
